WITH chn_0 AS MATERIALIZED (SELECT id, name FROM char_name AS chn),
ci_0 AS MATERIALIZED (SELECT movie_id, person_role_id, role_id FROM cast_info AS ci WHERE (ci.note LIKE '%(producer)%')),
cn_0 AS MATERIALIZED (SELECT id FROM company_name AS cn WHERE (cn.country_code = '[us]')),
ct_0 AS MATERIALIZED (SELECT id FROM company_type AS ct),
mc_0 AS MATERIALIZED (SELECT company_id, company_type_id, movie_id FROM movie_companies AS mc),
rt_0 AS MATERIALIZED (SELECT id FROM role_type AS rt),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t WHERE (t.production_year > 1990)),
ci_1 AS MATERIALIZED (SELECT * FROM ci_0 AS ci_t WHERE EXISTS (SELECT 1 FROM chn_0 AS chn_s WHERE chn_s.id = ci_t.person_role_id)),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM ct_0 AS ct_s WHERE ct_s.id = mc_t.company_type_id)),
ci_2 AS MATERIALIZED (SELECT * FROM ci_1 AS ci_t WHERE EXISTS (SELECT 1 FROM mc_2 AS mc_s WHERE mc_s.movie_id = ci_t.movie_id)),
ci_3 AS MATERIALIZED (SELECT * FROM ci_2 AS ci_t WHERE EXISTS (SELECT 1 FROM rt_0 AS rt_s WHERE rt_s.id = ci_t.role_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM ci_3 AS ci_s WHERE ci_s.movie_id = t_t.id)),
ci_4 AS MATERIALIZED (SELECT * FROM ci_3 AS ci_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = ci_t.movie_id)),
rt_1 AS MATERIALIZED (SELECT * FROM rt_0 AS rt_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.role_id = rt_t.id)),
mc_3 AS MATERIALIZED (SELECT * FROM mc_2 AS mc_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.movie_id = mc_t.movie_id)),
ct_1 AS MATERIALIZED (SELECT * FROM ct_0 AS ct_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_type_id = ct_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_id = cn_t.id)),
chn_1 AS MATERIALIZED (SELECT * FROM chn_0 AS chn_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.person_role_id = chn_t.id))
SELECT (SELECT MIN(name) FROM chn_1) AS character, (SELECT MIN(title) FROM t_1) AS movie_with_american_producer
