WITH cn_0 AS MATERIALIZED (SELECT id, name FROM company_name AS cn WHERE (cn.country_code !='[pl]') AND ((cn.name LIKE '%Film%'
       OR cn.name LIKE '%Warner%'))),
ct_0 AS MATERIALIZED (SELECT id FROM company_type AS ct WHERE (ct.kind ='production companies')),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k WHERE (k.keyword ='sequel')),
lt_0 AS MATERIALIZED (SELECT id, link FROM link_type AS lt WHERE (lt.link LIKE '%follow%')),
mc_0 AS MATERIALIZED (SELECT company_id, company_type_id, movie_id FROM movie_companies AS mc WHERE (mc.note IS NULL)),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
ml_0 AS MATERIALIZED (SELECT link_type_id, movie_id FROM movie_link AS ml),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t WHERE (t.production_year BETWEEN 1950 AND 2000)),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM ct_0 AS ct_s WHERE ct_s.id = mc_t.company_type_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
ml_1 AS MATERIALIZED (SELECT * FROM ml_0 AS ml_t WHERE EXISTS (SELECT 1 FROM lt_0 AS lt_s WHERE lt_s.id = ml_t.link_type_id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM mc_2 AS mc_s WHERE mc_s.movie_id = mk_t.movie_id)),
ml_2 AS MATERIALIZED (SELECT * FROM ml_1 AS ml_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.movie_id = ml_t.movie_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM ml_2 AS ml_s WHERE ml_s.movie_id = t_t.id)),
ml_3 AS MATERIALIZED (SELECT * FROM ml_2 AS ml_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = ml_t.movie_id)),
mk_3 AS MATERIALIZED (SELECT * FROM mk_2 AS mk_t WHERE EXISTS (SELECT 1 FROM ml_3 AS ml_s WHERE ml_s.movie_id = mk_t.movie_id)),
mc_3 AS MATERIALIZED (SELECT * FROM mc_2 AS mc_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.movie_id = mc_t.movie_id)),
lt_1 AS MATERIALIZED (SELECT * FROM lt_0 AS lt_t WHERE EXISTS (SELECT 1 FROM ml_3 AS ml_s WHERE ml_s.link_type_id = lt_t.id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
ct_1 AS MATERIALIZED (SELECT * FROM ct_0 AS ct_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_type_id = ct_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_id = cn_t.id))
SELECT (SELECT MIN(name) FROM cn_1) AS from_company, (SELECT MIN(link) FROM lt_1) AS movie_link_type, (SELECT MIN(title) FROM t_1) AS non_polish_sequel_movie
