WITH cn_0 AS MATERIALIZED (SELECT id FROM company_name AS cn WHERE (cn.country_code ='[us]')),
ct_0 AS MATERIALIZED (SELECT id FROM company_type AS ct WHERE (ct.kind IS NOT NULL) AND ((ct.kind ='production companies'
       OR ct.kind = 'distributors'))),
it1_0 AS MATERIALIZED (SELECT id FROM info_type AS it1 WHERE (it1.info ='budget')),
it2_0 AS MATERIALIZED (SELECT id FROM info_type AS it2 WHERE (it2.info ='bottom 10 rank')),
mc_0 AS MATERIALIZED (SELECT company_id, company_type_id, movie_id FROM movie_companies AS mc),
mi_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info AS mi),
mi_idx_0 AS MATERIALIZED (SELECT info_type_id, movie_id FROM movie_info_idx AS mi_idx),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t WHERE (t.production_year >2000) AND ((t.title LIKE 'Birdemic%'
       OR t.title LIKE '%Movie%'))),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM ct_0 AS ct_s WHERE ct_s.id = mc_t.company_type_id)),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it1_0 AS it1_s WHERE it1_s.id = mi_t.info_type_id)),
mi_idx_1 AS MATERIALIZED (SELECT * FROM mi_idx_0 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM it2_0 AS it2_s WHERE it2_s.id = mi_idx_t.info_type_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM mc_2 AS mc_s WHERE mc_s.movie_id = mi_t.movie_id)),
mi_idx_2 AS MATERIALIZED (SELECT * FROM mi_idx_1 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.movie_id = mi_idx_t.movie_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM mi_idx_2 AS mi_idx_s WHERE mi_idx_s.movie_id = t_t.id)),
mi_idx_3 AS MATERIALIZED (SELECT * FROM mi_idx_2 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = mi_idx_t.movie_id)),
mi_3 AS MATERIALIZED (SELECT * FROM mi_2 AS mi_t WHERE EXISTS (SELECT 1 FROM mi_idx_3 AS mi_idx_s WHERE mi_idx_s.movie_id = mi_t.movie_id)),
mc_3 AS MATERIALIZED (SELECT * FROM mc_2 AS mc_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.movie_id = mc_t.movie_id)),
it2_1 AS MATERIALIZED (SELECT * FROM it2_0 AS it2_t WHERE EXISTS (SELECT 1 FROM mi_idx_3 AS mi_idx_s WHERE mi_idx_s.info_type_id = it2_t.id)),
it1_1 AS MATERIALIZED (SELECT * FROM it1_0 AS it1_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.info_type_id = it1_t.id)),
ct_1 AS MATERIALIZED (SELECT * FROM ct_0 AS ct_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_type_id = ct_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_id = cn_t.id))
SELECT (SELECT MIN(info) FROM mi_3) AS budget, (SELECT MIN(title) FROM t_1) AS unsuccsessful_movie
