WITH cn_0 AS MATERIALIZED (SELECT id, name FROM company_name AS cn WHERE (cn.country_code ='[us]')),
ct_0 AS MATERIALIZED (SELECT id FROM company_type AS ct WHERE (ct.kind ='production companies')),
it_0 AS MATERIALIZED (SELECT id FROM info_type AS it WHERE (it.info ='rating')),
it2_0 AS MATERIALIZED (SELECT id FROM info_type AS it2 WHERE (it2.info ='release dates')),
kt_0 AS MATERIALIZED (SELECT id FROM kind_type AS kt WHERE (kt.kind ='movie')),
mc_0 AS MATERIALIZED (SELECT company_id, company_type_id, movie_id FROM movie_companies AS mc),
mi_0 AS MATERIALIZED (SELECT info_type_id, movie_id FROM movie_info AS mi),
miidx_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info_idx AS miidx),
t_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t WHERE (t.title != '') AND ((t.title LIKE 'Champion%'
       OR t.title LIKE 'Loser%'))),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM ct_0 AS ct_s WHERE ct_s.id = mc_t.company_type_id)),
miidx_1 AS MATERIALIZED (SELECT * FROM miidx_0 AS miidx_t WHERE EXISTS (SELECT 1 FROM it_0 AS it_s WHERE it_s.id = miidx_t.info_type_id)),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it2_0 AS it2_s WHERE it2_s.id = mi_t.info_type_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM kt_0 AS kt_s WHERE kt_s.id = t_t.kind_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM mc_2 AS mc_s WHERE mc_s.movie_id = mi_t.movie_id)),
miidx_2 AS MATERIALIZED (SELECT * FROM miidx_1 AS miidx_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.movie_id = miidx_t.movie_id)),
t_2 AS MATERIALIZED (SELECT * FROM t_1 AS t_t WHERE EXISTS (SELECT 1 FROM miidx_2 AS miidx_s WHERE miidx_s.movie_id = t_t.id)),
miidx_3 AS MATERIALIZED (SELECT * FROM miidx_2 AS miidx_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.id = miidx_t.movie_id)),
mi_3 AS MATERIALIZED (SELECT * FROM mi_2 AS mi_t WHERE EXISTS (SELECT 1 FROM miidx_3 AS miidx_s WHERE miidx_s.movie_id = mi_t.movie_id)),
mc_3 AS MATERIALIZED (SELECT * FROM mc_2 AS mc_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.movie_id = mc_t.movie_id)),
kt_1 AS MATERIALIZED (SELECT * FROM kt_0 AS kt_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.kind_id = kt_t.id)),
it2_1 AS MATERIALIZED (SELECT * FROM it2_0 AS it2_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.info_type_id = it2_t.id)),
it_1 AS MATERIALIZED (SELECT * FROM it_0 AS it_t WHERE EXISTS (SELECT 1 FROM miidx_3 AS miidx_s WHERE miidx_s.info_type_id = it_t.id)),
ct_1 AS MATERIALIZED (SELECT * FROM ct_0 AS ct_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_type_id = ct_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.company_id = cn_t.id))
SELECT (SELECT MIN(name) FROM cn_1) AS producing_company, (SELECT MIN(info) FROM miidx_3) AS rating, (SELECT MIN(title) FROM t_2) AS movie_about_winning
