WITH it1_0 AS MATERIALIZED (SELECT id FROM info_type AS it1 WHERE (it1.info = 'countries')),
it2_0 AS MATERIALIZED (SELECT id FROM info_type AS it2 WHERE (it2.info = 'rating')),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k WHERE (k.keyword IN ('murder',
                    'murder-in-title',
                    'blood',
                    'violence'))),
kt_0 AS MATERIALIZED (SELECT id FROM kind_type AS kt WHERE (kt.kind = 'movie')),
mi_0 AS MATERIALIZED (SELECT info_type_id, movie_id FROM movie_info AS mi WHERE (mi.info IN ('Sweden',
                  'Norway',
                  'Germany',
                  'Denmark',
                  'Swedish',
                  'Denish',
                  'Norwegian',
                  'German',
                  'USA',
                  'American'))),
mi_idx_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info_idx AS mi_idx WHERE (mi_idx.info < '8.5')),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
t_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t WHERE (t.production_year > 2010)),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it1_0 AS it1_s WHERE it1_s.id = mi_t.info_type_id)),
mi_idx_1 AS MATERIALIZED (SELECT * FROM mi_idx_0 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM it2_0 AS it2_s WHERE it2_s.id = mi_idx_t.info_type_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM kt_0 AS kt_s WHERE kt_s.id = t_t.kind_id)),
mi_idx_2 AS MATERIALIZED (SELECT * FROM mi_idx_1 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM mi_1 AS mi_s WHERE mi_s.movie_id = mi_idx_t.movie_id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM mi_idx_2 AS mi_idx_s WHERE mi_idx_s.movie_id = mk_t.movie_id)),
t_2 AS MATERIALIZED (SELECT * FROM t_1 AS t_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.movie_id = t_t.id)),
mk_3 AS MATERIALIZED (SELECT * FROM mk_2 AS mk_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.id = mk_t.movie_id)),
mi_idx_3 AS MATERIALIZED (SELECT * FROM mi_idx_2 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.movie_id = mi_idx_t.movie_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM mi_idx_3 AS mi_idx_s WHERE mi_idx_s.movie_id = mi_t.movie_id)),
kt_1 AS MATERIALIZED (SELECT * FROM kt_0 AS kt_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.kind_id = kt_t.id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
it2_1 AS MATERIALIZED (SELECT * FROM it2_0 AS it2_t WHERE EXISTS (SELECT 1 FROM mi_idx_3 AS mi_idx_s WHERE mi_idx_s.info_type_id = it2_t.id)),
it1_1 AS MATERIALIZED (SELECT * FROM it1_0 AS it1_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.info_type_id = it1_t.id))
SELECT (SELECT MIN(info) FROM mi_idx_3) AS rating, (SELECT MIN(title) FROM t_2) AS northern_dark_movie
