WITH at_0 AS MATERIALIZED (SELECT movie_id FROM aka_title AS "at"),
cn_0 AS MATERIALIZED (SELECT id FROM company_name AS cn WHERE (cn.country_code = '[us]')),
ct_0 AS MATERIALIZED (SELECT id FROM company_type AS ct),
it1_0 AS MATERIALIZED (SELECT id FROM info_type AS it1 WHERE (it1.info = 'release dates')),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k),
mc_0 AS MATERIALIZED (SELECT company_id, company_type_id, movie_id FROM movie_companies AS mc),
mi_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info AS mi WHERE (mi.note LIKE '%internet%') AND (mi.info IS NOT NULL) AND ((mi.info LIKE 'USA:% 199%'
       OR mi.info LIKE 'USA:% 200%'))),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t WHERE (t.production_year > 1990)),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM at_0 AS at_s WHERE at_s.movie_id = mc_t.movie_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mc_3 AS MATERIALIZED (SELECT * FROM mc_2 AS mc_t WHERE EXISTS (SELECT 1 FROM ct_0 AS ct_s WHERE ct_s.id = mc_t.company_type_id)),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it1_0 AS it1_s WHERE it1_s.id = mi_t.info_type_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.movie_id = mi_t.movie_id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.movie_id = mk_t.movie_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.movie_id = t_t.id)),
mk_3 AS MATERIALIZED (SELECT * FROM mk_2 AS mk_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = mk_t.movie_id)),
mi_3 AS MATERIALIZED (SELECT * FROM mi_2 AS mi_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.movie_id = mi_t.movie_id)),
mc_4 AS MATERIALIZED (SELECT * FROM mc_3 AS mc_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.movie_id = mc_t.movie_id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
it1_1 AS MATERIALIZED (SELECT * FROM it1_0 AS it1_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.info_type_id = it1_t.id)),
ct_1 AS MATERIALIZED (SELECT * FROM ct_0 AS ct_t WHERE EXISTS (SELECT 1 FROM mc_4 AS mc_s WHERE mc_s.company_type_id = ct_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_4 AS mc_s WHERE mc_s.company_id = cn_t.id)),
at_1 AS MATERIALIZED (SELECT * FROM at_0 AS at_t WHERE EXISTS (SELECT 1 FROM mc_4 AS mc_s WHERE mc_s.movie_id = at_t.movie_id))
SELECT (SELECT MIN(info) FROM mi_3) AS release_date, (SELECT MIN(title) FROM t_1) AS modern_american_internet_movie
