WITH ci_0 AS MATERIALIZED (SELECT movie_id, person_id FROM cast_info AS ci WHERE (ci.note IN ('(writer)',
                  '(head writer)',
                  '(written by)',
                  '(story)',
                  '(story editor)'))),
it1_0 AS MATERIALIZED (SELECT id FROM info_type AS it1 WHERE (it1.info = 'genres')),
it2_0 AS MATERIALIZED (SELECT id FROM info_type AS it2 WHERE (it2.info = 'votes')),
mi_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info AS mi WHERE (mi.info IN ('Horror',
                  'Action',
                  'Sci-Fi',
                  'Thriller',
                  'Crime',
                  'War'))),
mi_idx_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info_idx AS mi_idx),
n_0 AS MATERIALIZED (SELECT id FROM name AS n WHERE (n.gender = 'm')),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it1_0 AS it1_s WHERE it1_s.id = mi_t.info_type_id)),
mi_idx_1 AS MATERIALIZED (SELECT * FROM mi_idx_0 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM it2_0 AS it2_s WHERE it2_s.id = mi_idx_t.info_type_id)),
ci_1 AS MATERIALIZED (SELECT * FROM ci_0 AS ci_t WHERE EXISTS (SELECT 1 FROM mi_1 AS mi_s WHERE mi_s.movie_id = ci_t.movie_id)),
ci_2 AS MATERIALIZED (SELECT * FROM ci_1 AS ci_t WHERE EXISTS (SELECT 1 FROM mi_idx_1 AS mi_idx_s WHERE mi_idx_s.movie_id = ci_t.movie_id)),
ci_3 AS MATERIALIZED (SELECT * FROM ci_2 AS ci_t WHERE EXISTS (SELECT 1 FROM n_0 AS n_s WHERE n_s.id = ci_t.person_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM ci_3 AS ci_s WHERE ci_s.movie_id = t_t.id)),
ci_4 AS MATERIALIZED (SELECT * FROM ci_3 AS ci_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = ci_t.movie_id)),
n_1 AS MATERIALIZED (SELECT * FROM n_0 AS n_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.person_id = n_t.id)),
mi_idx_2 AS MATERIALIZED (SELECT * FROM mi_idx_1 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.movie_id = mi_idx_t.movie_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.movie_id = mi_t.movie_id)),
it2_1 AS MATERIALIZED (SELECT * FROM it2_0 AS it2_t WHERE EXISTS (SELECT 1 FROM mi_idx_2 AS mi_idx_s WHERE mi_idx_s.info_type_id = it2_t.id)),
it1_1 AS MATERIALIZED (SELECT * FROM it1_0 AS it1_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.info_type_id = it1_t.id))
SELECT (SELECT MIN(info) FROM mi_2) AS movie_budget, (SELECT MIN(info) FROM mi_idx_2) AS movie_votes, (SELECT MIN(title) FROM t_1) AS movie_title
