WITH cc_0 AS MATERIALIZED (SELECT movie_id, status_id, subject_id FROM complete_cast AS cc),
cct1_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct1 WHERE (cct1.kind = 'cast')),
cct2_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct2 WHERE (cct2.kind LIKE '%complete%')),
chn_0 AS MATERIALIZED (SELECT id FROM char_name AS chn WHERE (chn.name NOT LIKE '%Sherlock%') AND ((chn.name LIKE '%Tony%Stark%'
       OR chn.name LIKE '%Iron%Man%'))),
ci_0 AS MATERIALIZED (SELECT movie_id, person_id, person_role_id FROM cast_info AS ci),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k WHERE (k.keyword IN ('superhero',
                    'sequel',
                    'second-part',
                    'marvel-comics',
                    'based-on-comic',
                    'tv-special',
                    'fight',
                    'violence'))),
kt_0 AS MATERIALIZED (SELECT id FROM kind_type AS kt WHERE (kt.kind = 'movie')),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
n_0 AS MATERIALIZED (SELECT id FROM name AS n WHERE (n.name LIKE '%Downey%Robert%')),
t_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t WHERE (t.production_year > 2000)),
cc_1 AS MATERIALIZED (SELECT * FROM cc_0 AS cc_t WHERE EXISTS (SELECT 1 FROM cct1_0 AS cct1_s WHERE cct1_s.id = cc_t.subject_id)),
cc_2 AS MATERIALIZED (SELECT * FROM cc_1 AS cc_t WHERE EXISTS (SELECT 1 FROM cct2_0 AS cct2_s WHERE cct2_s.id = cc_t.status_id)),
ci_1 AS MATERIALIZED (SELECT * FROM ci_0 AS ci_t WHERE EXISTS (SELECT 1 FROM cc_2 AS cc_s WHERE cc_s.movie_id = ci_t.movie_id)),
ci_2 AS MATERIALIZED (SELECT * FROM ci_1 AS ci_t WHERE EXISTS (SELECT 1 FROM chn_0 AS chn_s WHERE chn_s.id = ci_t.person_role_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM kt_0 AS kt_s WHERE kt_s.id = t_t.kind_id)),
ci_3 AS MATERIALIZED (SELECT * FROM ci_2 AS ci_t WHERE EXISTS (SELECT 1 FROM mk_1 AS mk_s WHERE mk_s.movie_id = ci_t.movie_id)),
ci_4 AS MATERIALIZED (SELECT * FROM ci_3 AS ci_t WHERE EXISTS (SELECT 1 FROM n_0 AS n_s WHERE n_s.id = ci_t.person_id)),
t_2 AS MATERIALIZED (SELECT * FROM t_1 AS t_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.movie_id = t_t.id)),
ci_5 AS MATERIALIZED (SELECT * FROM ci_4 AS ci_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.id = ci_t.movie_id)),
n_1 AS MATERIALIZED (SELECT * FROM n_0 AS n_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.person_id = n_t.id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.movie_id = mk_t.movie_id)),
kt_1 AS MATERIALIZED (SELECT * FROM kt_0 AS kt_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.kind_id = kt_t.id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
chn_1 AS MATERIALIZED (SELECT * FROM chn_0 AS chn_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.person_role_id = chn_t.id)),
cc_3 AS MATERIALIZED (SELECT * FROM cc_2 AS cc_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.movie_id = cc_t.movie_id)),
cct2_1 AS MATERIALIZED (SELECT * FROM cct2_0 AS cct2_t WHERE EXISTS (SELECT 1 FROM cc_3 AS cc_s WHERE cc_s.status_id = cct2_t.id)),
cct1_1 AS MATERIALIZED (SELECT * FROM cct1_0 AS cct1_t WHERE EXISTS (SELECT 1 FROM cc_3 AS cc_s WHERE cc_s.subject_id = cct1_t.id))
SELECT (SELECT MIN(title) FROM t_2) AS complete_downey_ironman_movie
