WITH cc_0 AS MATERIALIZED (SELECT movie_id, status_id FROM complete_cast AS cc),
cct1_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct1 WHERE (cct1.kind = 'complete+verified')),
cn_0 AS MATERIALIZED (SELECT id FROM company_name AS cn WHERE (cn.country_code = '[us]')),
ct_0 AS MATERIALIZED (SELECT id FROM company_type AS ct),
it1_0 AS MATERIALIZED (SELECT id FROM info_type AS it1 WHERE (it1.info = 'release dates')),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k WHERE (k.keyword IN ('nerd',
                    'loner',
                    'alienation',
                    'dignity'))),
kt_0 AS MATERIALIZED (SELECT id, kind FROM kind_type AS kt WHERE (kt.kind IN ('movie'))),
mc_0 AS MATERIALIZED (SELECT company_id, company_type_id, movie_id FROM movie_companies AS mc),
mi_0 AS MATERIALIZED (SELECT info_type_id, movie_id FROM movie_info AS mi WHERE (mi.note LIKE '%internet%') AND (mi.info LIKE 'USA:% 200%')),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
t_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t WHERE (t.production_year > 2000)),
cc_1 AS MATERIALIZED (SELECT * FROM cc_0 AS cc_t WHERE EXISTS (SELECT 1 FROM cct1_0 AS cct1_s WHERE cct1_s.id = cc_t.status_id)),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cc_1 AS cc_s WHERE cc_s.movie_id = mc_t.movie_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mc_3 AS MATERIALIZED (SELECT * FROM mc_2 AS mc_t WHERE EXISTS (SELECT 1 FROM ct_0 AS ct_s WHERE ct_s.id = mc_t.company_type_id)),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it1_0 AS it1_s WHERE it1_s.id = mi_t.info_type_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM kt_0 AS kt_s WHERE kt_s.id = t_t.kind_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM mc_3 AS mc_s WHERE mc_s.movie_id = mi_t.movie_id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.movie_id = mk_t.movie_id)),
t_2 AS MATERIALIZED (SELECT * FROM t_1 AS t_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.movie_id = t_t.id)),
mk_3 AS MATERIALIZED (SELECT * FROM mk_2 AS mk_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.id = mk_t.movie_id)),
mi_3 AS MATERIALIZED (SELECT * FROM mi_2 AS mi_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.movie_id = mi_t.movie_id)),
mc_4 AS MATERIALIZED (SELECT * FROM mc_3 AS mc_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.movie_id = mc_t.movie_id)),
kt_1 AS MATERIALIZED (SELECT * FROM kt_0 AS kt_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.kind_id = kt_t.id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_3 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
it1_1 AS MATERIALIZED (SELECT * FROM it1_0 AS it1_t WHERE EXISTS (SELECT 1 FROM mi_3 AS mi_s WHERE mi_s.info_type_id = it1_t.id)),
ct_1 AS MATERIALIZED (SELECT * FROM ct_0 AS ct_t WHERE EXISTS (SELECT 1 FROM mc_4 AS mc_s WHERE mc_s.company_type_id = ct_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_4 AS mc_s WHERE mc_s.company_id = cn_t.id)),
cc_2 AS MATERIALIZED (SELECT * FROM cc_1 AS cc_t WHERE EXISTS (SELECT 1 FROM mc_4 AS mc_s WHERE mc_s.movie_id = cc_t.movie_id)),
cct1_1 AS MATERIALIZED (SELECT * FROM cct1_0 AS cct1_t WHERE EXISTS (SELECT 1 FROM cc_2 AS cc_s WHERE cc_s.status_id = cct1_t.id))
SELECT (SELECT MIN(kind) FROM kt_1) AS movie_kind, (SELECT MIN(title) FROM t_2) AS complete_nerdy_internet_movie
