WITH cc_0 AS MATERIALIZED (SELECT movie_id, status_id, subject_id FROM complete_cast AS cc),
cct1_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct1 WHERE (cct1.kind = 'cast')),
cct2_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct2 WHERE (cct2.kind LIKE '%complete%')),
chn_0 AS MATERIALIZED (SELECT id, name FROM char_name AS chn WHERE (chn.name IS NOT NULL) AND ((chn.name LIKE '%man%'
       OR chn.name LIKE '%Man%'))),
ci_0 AS MATERIALIZED (SELECT movie_id, person_id, person_role_id FROM cast_info AS ci),
it2_0 AS MATERIALIZED (SELECT id FROM info_type AS it2 WHERE (it2.info = 'rating')),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k WHERE (k.keyword IN ('superhero',
                    'marvel-comics',
                    'based-on-comic',
                    'tv-special',
                    'fight',
                    'violence',
                    'magnet',
                    'web',
                    'claw',
                    'laser'))),
kt_0 AS MATERIALIZED (SELECT id FROM kind_type AS kt WHERE (kt.kind = 'movie')),
mi_idx_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info_idx AS mi_idx WHERE (mi_idx.info > '7.0')),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
n_0 AS MATERIALIZED (SELECT id, name FROM name AS n),
t_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t WHERE (t.production_year > 2000)),
cc_1 AS MATERIALIZED (SELECT * FROM cc_0 AS cc_t WHERE EXISTS (SELECT 1 FROM cct1_0 AS cct1_s WHERE cct1_s.id = cc_t.subject_id)),
cc_2 AS MATERIALIZED (SELECT * FROM cc_1 AS cc_t WHERE EXISTS (SELECT 1 FROM cct2_0 AS cct2_s WHERE cct2_s.id = cc_t.status_id)),
ci_1 AS MATERIALIZED (SELECT * FROM ci_0 AS ci_t WHERE EXISTS (SELECT 1 FROM cc_2 AS cc_s WHERE cc_s.movie_id = ci_t.movie_id)),
ci_2 AS MATERIALIZED (SELECT * FROM ci_1 AS ci_t WHERE EXISTS (SELECT 1 FROM chn_0 AS chn_s WHERE chn_s.id = ci_t.person_role_id)),
mi_idx_1 AS MATERIALIZED (SELECT * FROM mi_idx_0 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM it2_0 AS it2_s WHERE it2_s.id = mi_idx_t.info_type_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM kt_0 AS kt_s WHERE kt_s.id = t_t.kind_id)),
ci_3 AS MATERIALIZED (SELECT * FROM ci_2 AS ci_t WHERE EXISTS (SELECT 1 FROM mi_idx_1 AS mi_idx_s WHERE mi_idx_s.movie_id = ci_t.movie_id)),
ci_4 AS MATERIALIZED (SELECT * FROM ci_3 AS ci_t WHERE EXISTS (SELECT 1 FROM mk_1 AS mk_s WHERE mk_s.movie_id = ci_t.movie_id)),
ci_5 AS MATERIALIZED (SELECT * FROM ci_4 AS ci_t WHERE EXISTS (SELECT 1 FROM n_0 AS n_s WHERE n_s.id = ci_t.person_id)),
t_2 AS MATERIALIZED (SELECT * FROM t_1 AS t_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.movie_id = t_t.id)),
ci_6 AS MATERIALIZED (SELECT * FROM ci_5 AS ci_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.id = ci_t.movie_id)),
n_1 AS MATERIALIZED (SELECT * FROM n_0 AS n_t WHERE EXISTS (SELECT 1 FROM ci_6 AS ci_s WHERE ci_s.person_id = n_t.id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM ci_6 AS ci_s WHERE ci_s.movie_id = mk_t.movie_id)),
mi_idx_2 AS MATERIALIZED (SELECT * FROM mi_idx_1 AS mi_idx_t WHERE EXISTS (SELECT 1 FROM ci_6 AS ci_s WHERE ci_s.movie_id = mi_idx_t.movie_id)),
kt_1 AS MATERIALIZED (SELECT * FROM kt_0 AS kt_t WHERE EXISTS (SELECT 1 FROM t_2 AS t_s WHERE t_s.kind_id = kt_t.id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
it2_1 AS MATERIALIZED (SELECT * FROM it2_0 AS it2_t WHERE EXISTS (SELECT 1 FROM mi_idx_2 AS mi_idx_s WHERE mi_idx_s.info_type_id = it2_t.id)),
chn_1 AS MATERIALIZED (SELECT * FROM chn_0 AS chn_t WHERE EXISTS (SELECT 1 FROM ci_6 AS ci_s WHERE ci_s.person_role_id = chn_t.id)),
cc_3 AS MATERIALIZED (SELECT * FROM cc_2 AS cc_t WHERE EXISTS (SELECT 1 FROM ci_6 AS ci_s WHERE ci_s.movie_id = cc_t.movie_id)),
cct2_1 AS MATERIALIZED (SELECT * FROM cct2_0 AS cct2_t WHERE EXISTS (SELECT 1 FROM cc_3 AS cc_s WHERE cc_s.status_id = cct2_t.id)),
cct1_1 AS MATERIALIZED (SELECT * FROM cct1_0 AS cct1_t WHERE EXISTS (SELECT 1 FROM cc_3 AS cc_s WHERE cc_s.subject_id = cct1_t.id))
SELECT (SELECT MIN(name) FROM chn_1) AS character_name, (SELECT MIN(info) FROM mi_idx_2) AS rating, (SELECT MIN(name) FROM n_1) AS playing_actor, (SELECT MIN(title) FROM t_2) AS complete_hero_movie
