WITH an_0 AS MATERIALIZED (SELECT person_id FROM aka_name AS an),
cc_0 AS MATERIALIZED (SELECT movie_id, status_id, subject_id FROM complete_cast AS cc),
cct1_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct1 WHERE (cct1.kind ='cast')),
cct2_0 AS MATERIALIZED (SELECT id FROM comp_cast_type AS cct2 WHERE (cct2.kind ='complete+verified')),
chn_0 AS MATERIALIZED (SELECT id, name FROM char_name AS chn WHERE (chn.name = 'Queen')),
ci_0 AS MATERIALIZED (SELECT movie_id, person_id, person_role_id, role_id FROM cast_info AS ci WHERE (ci.note IN ('(voice)',
                  '(voice) (uncredited)',
                  '(voice: English version)'))),
cn_0 AS MATERIALIZED (SELECT id FROM company_name AS cn WHERE (cn.country_code ='[us]')),
it_0 AS MATERIALIZED (SELECT id FROM info_type AS it WHERE (it.info = 'release dates')),
it3_0 AS MATERIALIZED (SELECT id FROM info_type AS it3 WHERE (it3.info = 'height')),
k_0 AS MATERIALIZED (SELECT id FROM keyword AS k WHERE (k.keyword = 'computer-animation')),
mc_0 AS MATERIALIZED (SELECT company_id, movie_id FROM movie_companies AS mc),
mi_0 AS MATERIALIZED (SELECT info_type_id, movie_id FROM movie_info AS mi WHERE (mi.info LIKE 'USA:%200%')),
mk_0 AS MATERIALIZED (SELECT keyword_id, movie_id FROM movie_keyword AS mk),
n_0 AS MATERIALIZED (SELECT id, name FROM name AS n WHERE (n.gender ='f') AND (n.name LIKE '%An%')),
pi_0 AS MATERIALIZED (SELECT info_type_id, person_id FROM person_info AS pi),
rt_0 AS MATERIALIZED (SELECT id FROM role_type AS rt WHERE (rt.role ='actress')),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t WHERE (t.title = 'Shrek 2') AND (t.production_year BETWEEN 2000 AND 2005)),
ci_1 AS MATERIALIZED (SELECT * FROM ci_0 AS ci_t WHERE EXISTS (SELECT 1 FROM an_0 AS an_s WHERE an_s.person_id = ci_t.person_id)),
cc_1 AS MATERIALIZED (SELECT * FROM cc_0 AS cc_t WHERE EXISTS (SELECT 1 FROM cct1_0 AS cct1_s WHERE cct1_s.id = cc_t.subject_id)),
cc_2 AS MATERIALIZED (SELECT * FROM cc_1 AS cc_t WHERE EXISTS (SELECT 1 FROM cct2_0 AS cct2_s WHERE cct2_s.id = cc_t.status_id)),
ci_2 AS MATERIALIZED (SELECT * FROM ci_1 AS ci_t WHERE EXISTS (SELECT 1 FROM cc_2 AS cc_s WHERE cc_s.movie_id = ci_t.movie_id)),
ci_3 AS MATERIALIZED (SELECT * FROM ci_2 AS ci_t WHERE EXISTS (SELECT 1 FROM chn_0 AS chn_s WHERE chn_s.id = ci_t.person_role_id)),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
mi_1 AS MATERIALIZED (SELECT * FROM mi_0 AS mi_t WHERE EXISTS (SELECT 1 FROM it_0 AS it_s WHERE it_s.id = mi_t.info_type_id)),
pi_1 AS MATERIALIZED (SELECT * FROM pi_0 AS pi_t WHERE EXISTS (SELECT 1 FROM it3_0 AS it3_s WHERE it3_s.id = pi_t.info_type_id)),
mk_1 AS MATERIALIZED (SELECT * FROM mk_0 AS mk_t WHERE EXISTS (SELECT 1 FROM k_0 AS k_s WHERE k_s.id = mk_t.keyword_id)),
ci_4 AS MATERIALIZED (SELECT * FROM ci_3 AS ci_t WHERE EXISTS (SELECT 1 FROM mc_1 AS mc_s WHERE mc_s.movie_id = ci_t.movie_id)),
ci_5 AS MATERIALIZED (SELECT * FROM ci_4 AS ci_t WHERE EXISTS (SELECT 1 FROM mi_1 AS mi_s WHERE mi_s.movie_id = ci_t.movie_id)),
ci_6 AS MATERIALIZED (SELECT * FROM ci_5 AS ci_t WHERE EXISTS (SELECT 1 FROM mk_1 AS mk_s WHERE mk_s.movie_id = ci_t.movie_id)),
ci_7 AS MATERIALIZED (SELECT * FROM ci_6 AS ci_t WHERE EXISTS (SELECT 1 FROM n_0 AS n_s WHERE n_s.id = ci_t.person_id)),
ci_8 AS MATERIALIZED (SELECT * FROM ci_7 AS ci_t WHERE EXISTS (SELECT 1 FROM pi_1 AS pi_s WHERE pi_s.person_id = ci_t.person_id)),
ci_9 AS MATERIALIZED (SELECT * FROM ci_8 AS ci_t WHERE EXISTS (SELECT 1 FROM rt_0 AS rt_s WHERE rt_s.id = ci_t.role_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM ci_9 AS ci_s WHERE ci_s.movie_id = t_t.id)),
ci_10 AS MATERIALIZED (SELECT * FROM ci_9 AS ci_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = ci_t.movie_id)),
rt_1 AS MATERIALIZED (SELECT * FROM rt_0 AS rt_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.role_id = rt_t.id)),
pi_2 AS MATERIALIZED (SELECT * FROM pi_1 AS pi_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.person_id = pi_t.person_id)),
n_1 AS MATERIALIZED (SELECT * FROM n_0 AS n_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.person_id = n_t.id)),
mk_2 AS MATERIALIZED (SELECT * FROM mk_1 AS mk_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.movie_id = mk_t.movie_id)),
mi_2 AS MATERIALIZED (SELECT * FROM mi_1 AS mi_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.movie_id = mi_t.movie_id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.movie_id = mc_t.movie_id)),
k_1 AS MATERIALIZED (SELECT * FROM k_0 AS k_t WHERE EXISTS (SELECT 1 FROM mk_2 AS mk_s WHERE mk_s.keyword_id = k_t.id)),
it3_1 AS MATERIALIZED (SELECT * FROM it3_0 AS it3_t WHERE EXISTS (SELECT 1 FROM pi_2 AS pi_s WHERE pi_s.info_type_id = it3_t.id)),
it_1 AS MATERIALIZED (SELECT * FROM it_0 AS it_t WHERE EXISTS (SELECT 1 FROM mi_2 AS mi_s WHERE mi_s.info_type_id = it_t.id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_2 AS mc_s WHERE mc_s.company_id = cn_t.id)),
chn_1 AS MATERIALIZED (SELECT * FROM chn_0 AS chn_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.person_role_id = chn_t.id)),
cc_3 AS MATERIALIZED (SELECT * FROM cc_2 AS cc_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.movie_id = cc_t.movie_id)),
cct2_1 AS MATERIALIZED (SELECT * FROM cct2_0 AS cct2_t WHERE EXISTS (SELECT 1 FROM cc_3 AS cc_s WHERE cc_s.status_id = cct2_t.id)),
cct1_1 AS MATERIALIZED (SELECT * FROM cct1_0 AS cct1_t WHERE EXISTS (SELECT 1 FROM cc_3 AS cc_s WHERE cc_s.subject_id = cct1_t.id)),
an_1 AS MATERIALIZED (SELECT * FROM an_0 AS an_t WHERE EXISTS (SELECT 1 FROM ci_10 AS ci_s WHERE ci_s.person_id = an_t.person_id))
SELECT (SELECT MIN(name) FROM chn_1) AS voiced_char, (SELECT MIN(name) FROM n_1) AS voicing_actress, (SELECT MIN(title) FROM t_1) AS voiced_animation
