WITH cn1_0 AS MATERIALIZED (SELECT id, name FROM company_name AS cn1 WHERE (cn1.country_code != '[us]')),
cn2_0 AS MATERIALIZED (SELECT id, name FROM company_name AS cn2),
it1_0 AS MATERIALIZED (SELECT id FROM info_type AS it1 WHERE (it1.info = 'rating')),
it2_0 AS MATERIALIZED (SELECT id FROM info_type AS it2 WHERE (it2.info = 'rating')),
kt1_0 AS MATERIALIZED (SELECT id FROM kind_type AS kt1 WHERE (kt1.kind IN ('tv series',
                   'episode'))),
kt2_0 AS MATERIALIZED (SELECT id FROM kind_type AS kt2 WHERE (kt2.kind IN ('tv series',
                   'episode'))),
lt_0 AS MATERIALIZED (SELECT id FROM link_type AS lt WHERE (lt.link IN ('sequel',
                  'follows',
                  'followed by'))),
mc1_0 AS MATERIALIZED (SELECT company_id, movie_id FROM movie_companies AS mc1),
mc2_0 AS MATERIALIZED (SELECT company_id, movie_id FROM movie_companies AS mc2),
mi_idx1_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info_idx AS mi_idx1),
mi_idx2_0 AS MATERIALIZED (SELECT info, info_type_id, movie_id FROM movie_info_idx AS mi_idx2 WHERE (mi_idx2.info < '3.5')),
ml_0 AS MATERIALIZED (SELECT link_type_id, linked_movie_id, movie_id FROM movie_link AS ml),
t1_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t1),
t2_0 AS MATERIALIZED (SELECT id, kind_id, title FROM title AS t2 WHERE (t2.production_year BETWEEN 2000 AND 2010)),
mc1_1 AS MATERIALIZED (SELECT * FROM mc1_0 AS mc1_t WHERE EXISTS (SELECT 1 FROM cn1_0 AS cn1_s WHERE cn1_s.id = mc1_t.company_id)),
mc2_1 AS MATERIALIZED (SELECT * FROM mc2_0 AS mc2_t WHERE EXISTS (SELECT 1 FROM cn2_0 AS cn2_s WHERE cn2_s.id = mc2_t.company_id)),
mi_idx1_1 AS MATERIALIZED (SELECT * FROM mi_idx1_0 AS mi_idx1_t WHERE EXISTS (SELECT 1 FROM it1_0 AS it1_s WHERE it1_s.id = mi_idx1_t.info_type_id)),
mi_idx2_1 AS MATERIALIZED (SELECT * FROM mi_idx2_0 AS mi_idx2_t WHERE EXISTS (SELECT 1 FROM it2_0 AS it2_s WHERE it2_s.id = mi_idx2_t.info_type_id)),
t1_1 AS MATERIALIZED (SELECT * FROM t1_0 AS t1_t WHERE EXISTS (SELECT 1 FROM kt1_0 AS kt1_s WHERE kt1_s.id = t1_t.kind_id)),
t2_1 AS MATERIALIZED (SELECT * FROM t2_0 AS t2_t WHERE EXISTS (SELECT 1 FROM kt2_0 AS kt2_s WHERE kt2_s.id = t2_t.kind_id)),
ml_1 AS MATERIALIZED (SELECT * FROM ml_0 AS ml_t WHERE EXISTS (SELECT 1 FROM lt_0 AS lt_s WHERE lt_s.id = ml_t.link_type_id)),
mi_idx1_2 AS MATERIALIZED (SELECT * FROM mi_idx1_1 AS mi_idx1_t WHERE EXISTS (SELECT 1 FROM mc1_1 AS mc1_s WHERE mc1_s.movie_id = mi_idx1_t.movie_id)),
mi_idx2_2 AS MATERIALIZED (SELECT * FROM mi_idx2_1 AS mi_idx2_t WHERE EXISTS (SELECT 1 FROM mc2_1 AS mc2_s WHERE mc2_s.movie_id = mi_idx2_t.movie_id)),
ml_2 AS MATERIALIZED (SELECT * FROM ml_1 AS ml_t WHERE EXISTS (SELECT 1 FROM mi_idx1_2 AS mi_idx1_s WHERE mi_idx1_s.movie_id = ml_t.movie_id)),
ml_3 AS MATERIALIZED (SELECT * FROM ml_2 AS ml_t WHERE EXISTS (SELECT 1 FROM mi_idx2_2 AS mi_idx2_s WHERE mi_idx2_s.movie_id = ml_t.linked_movie_id)),
ml_4 AS MATERIALIZED (SELECT * FROM ml_3 AS ml_t WHERE EXISTS (SELECT 1 FROM t1_1 AS t1_s WHERE t1_s.id = ml_t.movie_id)),
t2_2 AS MATERIALIZED (SELECT * FROM t2_1 AS t2_t WHERE EXISTS (SELECT 1 FROM ml_4 AS ml_s WHERE ml_s.linked_movie_id = t2_t.id)),
ml_5 AS MATERIALIZED (SELECT * FROM ml_4 AS ml_t WHERE EXISTS (SELECT 1 FROM t2_2 AS t2_s WHERE t2_s.id = ml_t.linked_movie_id)),
t1_2 AS MATERIALIZED (SELECT * FROM t1_1 AS t1_t WHERE EXISTS (SELECT 1 FROM ml_5 AS ml_s WHERE ml_s.movie_id = t1_t.id)),
mi_idx2_3 AS MATERIALIZED (SELECT * FROM mi_idx2_2 AS mi_idx2_t WHERE EXISTS (SELECT 1 FROM ml_5 AS ml_s WHERE ml_s.linked_movie_id = mi_idx2_t.movie_id)),
mi_idx1_3 AS MATERIALIZED (SELECT * FROM mi_idx1_2 AS mi_idx1_t WHERE EXISTS (SELECT 1 FROM ml_5 AS ml_s WHERE ml_s.movie_id = mi_idx1_t.movie_id)),
mc2_2 AS MATERIALIZED (SELECT * FROM mc2_1 AS mc2_t WHERE EXISTS (SELECT 1 FROM mi_idx2_3 AS mi_idx2_s WHERE mi_idx2_s.movie_id = mc2_t.movie_id)),
mc1_2 AS MATERIALIZED (SELECT * FROM mc1_1 AS mc1_t WHERE EXISTS (SELECT 1 FROM mi_idx1_3 AS mi_idx1_s WHERE mi_idx1_s.movie_id = mc1_t.movie_id)),
lt_1 AS MATERIALIZED (SELECT * FROM lt_0 AS lt_t WHERE EXISTS (SELECT 1 FROM ml_5 AS ml_s WHERE ml_s.link_type_id = lt_t.id)),
kt2_1 AS MATERIALIZED (SELECT * FROM kt2_0 AS kt2_t WHERE EXISTS (SELECT 1 FROM t2_2 AS t2_s WHERE t2_s.kind_id = kt2_t.id)),
kt1_1 AS MATERIALIZED (SELECT * FROM kt1_0 AS kt1_t WHERE EXISTS (SELECT 1 FROM t1_2 AS t1_s WHERE t1_s.kind_id = kt1_t.id)),
it2_1 AS MATERIALIZED (SELECT * FROM it2_0 AS it2_t WHERE EXISTS (SELECT 1 FROM mi_idx2_3 AS mi_idx2_s WHERE mi_idx2_s.info_type_id = it2_t.id)),
it1_1 AS MATERIALIZED (SELECT * FROM it1_0 AS it1_t WHERE EXISTS (SELECT 1 FROM mi_idx1_3 AS mi_idx1_s WHERE mi_idx1_s.info_type_id = it1_t.id)),
cn2_1 AS MATERIALIZED (SELECT * FROM cn2_0 AS cn2_t WHERE EXISTS (SELECT 1 FROM mc2_2 AS mc2_s WHERE mc2_s.company_id = cn2_t.id)),
cn1_1 AS MATERIALIZED (SELECT * FROM cn1_0 AS cn1_t WHERE EXISTS (SELECT 1 FROM mc1_2 AS mc1_s WHERE mc1_s.company_id = cn1_t.id))
SELECT (SELECT MIN(name) FROM cn1_1) AS first_company, (SELECT MIN(name) FROM cn2_1) AS second_company, (SELECT MIN(info) FROM mi_idx1_3) AS first_rating, (SELECT MIN(info) FROM mi_idx2_3) AS second_rating, (SELECT MIN(title) FROM t1_2) AS first_movie, (SELECT MIN(title) FROM t2_2) AS second_movie
