WITH a1_0 AS MATERIALIZED (SELECT name, person_id FROM aka_name AS a1),
ci_0 AS MATERIALIZED (SELECT movie_id, person_id, role_id FROM cast_info AS ci),
cn_0 AS MATERIALIZED (SELECT id FROM company_name AS cn WHERE (cn.country_code ='[us]')),
mc_0 AS MATERIALIZED (SELECT company_id, movie_id FROM movie_companies AS mc),
n1_0 AS MATERIALIZED (SELECT id FROM name AS n1),
rt_0 AS MATERIALIZED (SELECT id FROM role_type AS rt WHERE (rt.role ='writer')),
t_0 AS MATERIALIZED (SELECT id, title FROM title AS t),
ci_1 AS MATERIALIZED (SELECT * FROM ci_0 AS ci_t WHERE EXISTS (SELECT 1 FROM a1_0 AS a1_s WHERE a1_s.person_id = ci_t.person_id)),
mc_1 AS MATERIALIZED (SELECT * FROM mc_0 AS mc_t WHERE EXISTS (SELECT 1 FROM cn_0 AS cn_s WHERE cn_s.id = mc_t.company_id)),
ci_2 AS MATERIALIZED (SELECT * FROM ci_1 AS ci_t WHERE EXISTS (SELECT 1 FROM mc_1 AS mc_s WHERE mc_s.movie_id = ci_t.movie_id)),
ci_3 AS MATERIALIZED (SELECT * FROM ci_2 AS ci_t WHERE EXISTS (SELECT 1 FROM n1_0 AS n1_s WHERE n1_s.id = ci_t.person_id)),
ci_4 AS MATERIALIZED (SELECT * FROM ci_3 AS ci_t WHERE EXISTS (SELECT 1 FROM rt_0 AS rt_s WHERE rt_s.id = ci_t.role_id)),
t_1 AS MATERIALIZED (SELECT * FROM t_0 AS t_t WHERE EXISTS (SELECT 1 FROM ci_4 AS ci_s WHERE ci_s.movie_id = t_t.id)),
ci_5 AS MATERIALIZED (SELECT * FROM ci_4 AS ci_t WHERE EXISTS (SELECT 1 FROM t_1 AS t_s WHERE t_s.id = ci_t.movie_id)),
rt_1 AS MATERIALIZED (SELECT * FROM rt_0 AS rt_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.role_id = rt_t.id)),
n1_1 AS MATERIALIZED (SELECT * FROM n1_0 AS n1_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.person_id = n1_t.id)),
mc_2 AS MATERIALIZED (SELECT * FROM mc_1 AS mc_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.movie_id = mc_t.movie_id)),
cn_1 AS MATERIALIZED (SELECT * FROM cn_0 AS cn_t WHERE EXISTS (SELECT 1 FROM mc_2 AS mc_s WHERE mc_s.company_id = cn_t.id)),
a1_1 AS MATERIALIZED (SELECT * FROM a1_0 AS a1_t WHERE EXISTS (SELECT 1 FROM ci_5 AS ci_s WHERE ci_s.person_id = a1_t.person_id))
SELECT (SELECT MIN(name) FROM a1_1) AS writer_pseudo_name, (SELECT MIN(title) FROM t_1) AS movie_title
